fun main(){
    print("Student Enrollment No.: ")
    var en = readLine()!!.toLong()
    print("Student Name: ")
    var name = readLine()
    print("Student Branch: ")
    var branch = readLine()
    print("Student Class: ")
    var cls = readLine()
    print("Student Batch: ")
    var bch = readLine()
    print("Student College Name: ")
    var clg_name = readLine()
    print("Student University Name: ")
    var uni_name = readLine()
    print("Student Age: ")
    var age = readLine()!!.toInt()

    println()
    println("*******************")
    println()

    println("Students Data:")
    println("Enrollment N0.: $en")
    println("Name: $name")
    println("Age: $age")
    println("Branch: $branch")
    println("Class: $cls")
    println("Batch: $bch")
    println("College Name: $clg_name")
    println("University Name: $uni_name")
}